# fly.toml file generated for am-wg-proxy-slow on 2022-09-10T08:25:41-04:00

app = "am-wg-proxy-fast"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  LEGACY_USERS_API_URL = "https://api.aftermath.link/api/users/v1"
  PORT = "80"
  PROXY_HOST_LIST = "168.91.93.2:21326,192.154.206.250:21258,172.98.171.35:21329,198.37.124.130:21296,172.82.181.204:21312"
  PROXY_HOST_MAX_RPS = "20"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 80