app = "am-wg-proxy"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "registry.fly.io/am-wg-proxy:latest"

[env]
  PROXY_HOST_MAX_RPS="20"
  PROXY_HOST_LIST="136.0.116.10:4444,185.182.65.90:4444,136.0.116.169:4444,185.182.65.91:4444,45.39.255.177:4444"
  LEGACY_USERS_API_URL="https://api.aftermath.link/api/users/v1"
  TAILSCALE_APP_NAME="am-wg-proxy"
  PORT="80"

[experimental]
  auto_rollback = true