# fly.toml app configuration file generated for aftermath-wg-proxy-live on 2024-02-01T15:22:12-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aftermath-wg-proxy-live'
primary_region = 'lhr'

[env]
FALLBACK_MAX_RPS = '10'
LOG_LEVEL = 'info'
NETWORK = 'tcp'
PORT = '9090'

[[vm]]
cpu_kind = 'shared'
cpus = 2
memory_mb = 512
