# fly.toml file generated for am-wg-proxy-slow on 2022-09-10T08:25:41-04:00

app = "am-wg-proxy-slow"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  LEGACY_USERS_API_URL = "https://api.aftermath.link/api/users/v1"
  PORT = "80"
  PROXY_HOST_LIST = "136.0.116.10:4444,185.182.65.90:4444,136.0.116.169:4444,185.182.65.91:4444,45.39.255.177:4444"
  PROXY_HOST_MAX_RPS = "20"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 80