version: "3"

dotenv: ['.env']

tasks:
  dev:
    desc: Run the application in development mode with hot reload
    cmds:
      - air
  test:
    desc: Run tests
    cmds:
      - go test ./... -v          
  upgrade:
    desc: Upgrade dependencies
    cmds:
      - go get -u ./...

  tag:
    desc: Tag the current commit
    cmds:
      - git tag -a {{.CLI_ARGS}} -m "Version {{.CLI_ARGS}}"
      - git push --tags
  tags:
    desc: Get the latest git tag
    cmds:
      - git describe --abbrev=0

  deploy:
    desc: Deploy the application
    cmds:
      - fly deploy -c cache.fly.toml & fly deploy -c live.fly.toml

  build:docker:
    desc: Build the application for Docker
    cmds:
      - go build -o {{ .CLI_ARGS | default "app" }} .
  build:image:
    desc: Build the Docker image
    cmds:
      - docker build --progress=plain --platform linux/amd64 -t {{ .CLI_ARGS | default "github.com/cufee/am-wg-proxy-next" }} .