version: "3"

vars:
  VERSION:
    sh: git rev-parse --short HEAD

env:
  BASE_APP_NAME: am-wg-proxy
  NAMESPACE: aftermath-wargaming
  REGISTRY: us-east4-docker.pkg.dev/aftermath-327212/aftermath-images
  K8S_TYPE: deployment

tasks:
  build:
    desc: Build, tag and load the image
    cmds:
      - docker buildx build --platform linux/amd64 -t $REGISTRY/$BASE_APP_NAME:{{.VERSION}} -t $REGISTRY/$BASE_APP_NAME:latest --{{.CLI_ARGS | default "push"}} --secret id=ssh_priv,src=$HOME/.ssh/id_rsa --secret id=ssh_pub,src=$HOME/.ssh/id_rsa.pub .

  restart:
    desc: Restart k8s deployment
    cmds:
      - kubectl rollout restart $K8S_TYPE/$BASE_APP_NAME-internal -n $NAMESPACE

  tag:
    desc: Tag the current commit
    cmds:
      - git tag -a {{.CLI_ARGS}} -m "Version {{.CLI_ARGS}}"
      - git push --tags
  tags:
    desc: Get the latest git tag
    cmds:
      - git describe --abbrev=0
