package accounts

type BaseDetails struct {
	Nickname  string `json:"nickname"`
	AccountID int    `json:"account_id"`
}

// VehicleStats - Player Vehicle stats struct, used to return final data
type VehicleStats struct {
	StatsFrame     `json:"all" bson:"all"`
	LastBattleTime int    `json:"last_battle_time" bson:"last_battle_time"`
	MarkOfMastery  int    `json:"mark_of_mastery" bson:"mark_of_mastery"`
	TankID         int    `json:"tank_id" bson:"tank_id"`
	TankTier       int    `json:"tank_tier" bson:"tank_tier"`
	TankName       string `json:"tank_name" bson:"tank_name"`
	TankWN8        int    `json:"tank_wn8,omitempty" bson:"tank_wn8,omitempty"`
	TankRawWN8     int    `json:"tank_raw_wn8,omitempty" bson:"tank_raw_wn8,omitempty"`
}

type StatsFrame struct {
	Rating               float64 `json:"mm_rating" bson:"mm_rating"`
	Spotted              int     `json:"spotted" bson:"spotted"`
	Hits                 int     `json:"hits" bson:"hits"`
	Frags                int     `json:"frags" bson:"frags"`
	MaxXp                int     `json:"max_xp" bson:"max_xp"`
	Wins                 int     `json:"wins" bson:"wins"`
	Losses               int     `json:"losses" bson:"losses"`
	CapturePoints        int     `json:"capture_points" bson:"capture_points"`
	Battles              int     `json:"battles" bson:"battles"`
	DamageDealt          int     `json:"damage_dealt" bson:"damage_dealt"`
	DamageReceived       int     `json:"damage_received" bson:"damage_received"`
	MaxFrags             int     `json:"max_frags" bson:"max_frags"`
	Shots                int     `json:"shots" bson:"shots"`
	Xp                   int     `json:"xp" bson:"xp"`
	SurvivedBattles      int     `json:"survived_battles" bson:"survived_battles"`
	DroppedCapturePoints int     `json:"dropped_capture_points" bson:"dropped_capture_points"`
}

type AchievementsFrame struct {
	Achievements struct {
		ArmorPiercer                int `json:"armorpiercer,omitempty" bson:"armorpiercer,omitempty"`
		MedalFadin                  int `json:"medalfadin,omitempty" bson:"medalfadin,omitempty"`
		MedalCarius                 int `json:"medalcarius,omitempty" bson:"medalcarius,omitempty"`
		MedalEkins                  int `json:"medalekins,omitempty" bson:"medalekins,omitempty"`
		CollectorGuP                int `json:"collectorgup,omitempty" bson:"collectorgup,omitempty"`
		MedalHalonen                int `json:"medalhalonen,omitempty" bson:"medalhalonen,omitempty"`
		HeroesOfRassenay            int `json:"heroesofrassenay,omitempty" bson:"heroesofrassenay,omitempty"`
		FirstVictory                int `json:"firstvictory,omitempty" bson:"firstvictory,omitempty"`
		Defender                    int `json:"defender,omitempty" bson:"defender,omitempty"`
		Creative                    int `json:"creative,omitempty" bson:"creative,omitempty"`
		ESportFinal                 int `json:"esportfinal,omitempty" bson:"esportfinal,omitempty"`
		Supporter                   int `json:"supporter,omitempty" bson:"supporter,omitempty"`
		GoldClanRibbonSEA           int `json:"goldclanribbonsea,omitempty" bson:"goldclanribbonsea,omitempty"`
		PlatinumTwisterMedalSEA     int `json:"platinumtwistermedalsea,omitempty" bson:"platinumtwistermedalsea,omitempty"`
		MedalLehvaslaiho            int `json:"medallehvaslaiho,omitempty" bson:"medallehvaslaiho,omitempty"`
		TankExpert                  int `json:"tankexpert,omitempty" bson:"tankexpert,omitempty"`
		ESportQualification         int `json:"esportqualification,omitempty" bson:"esportqualification,omitempty"`
		MarkI                       int `json:"marki,omitempty" bson:"marki,omitempty"`
		MedalSupremacy              int `json:"medalsupremacy,omitempty" bson:"medalsupremacy,omitempty"`
		ParticipantofWGFest2017     int `json:"participantofwgfest2017,omitempty" bson:"participantofwgfest2017,omitempty"`
		MedalTournamentOffseason1   int `json:"medaltournamentoffseason1,omitempty" bson:"medaltournamentoffseason1,omitempty"`
		JointVictory                int `json:"jointvictory,omitempty" bson:"jointvictory,omitempty"`
		MedalTournamentOffseason2   int `json:"medaltournamentoffseason2,omitempty" bson:"medaltournamentoffseason2,omitempty"`
		MedalTournamentOffseason4   int `json:"medaltournamentoffseason4,omitempty" bson:"medaltournamentoffseason4,omitempty"`
		Sniper                      int `json:"sniper,omitempty" bson:"sniper,omitempty"`
		TitleSniper                 int `json:"titlesniper,omitempty" bson:"titlesniper,omitempty"`
		MedalCrucialContribution    int `json:"medalcrucialcontribution,omitempty" bson:"medalcrucialcontribution,omitempty"`
		Scout                       int `json:"scout,omitempty" bson:"scout,omitempty"`
		GoldTwisterMedalRU          int `json:"goldtwistermedalru,omitempty" bson:"goldtwistermedalru,omitempty"`
		TankExpert3                 int `json:"tankexpert3,omitempty" bson:"tankexpert3,omitempty"`
		TankExpert2                 int `json:"tankexpert2,omitempty" bson:"tankexpert2,omitempty"`
		TankExpert1                 int `json:"tankexpert1,omitempty" bson:"tankexpert1,omitempty"`
		TankExpert0                 int `json:"tankexpert0,omitempty" bson:"tankexpert0,omitempty"`
		MarkOfMastery               int `json:"markofmastery,omitempty" bson:"markofmastery,omitempty"`
		TankExpert6                 int `json:"tankexpert6,omitempty" bson:"tankexpert6,omitempty"`
		TankExpert5                 int `json:"tankexpert5,omitempty" bson:"tankexpert5,omitempty"`
		TankExpert4                 int `json:"tankexpert4,omitempty" bson:"tankexpert4,omitempty"`
		GoldTwisterMedalEU          int `json:"goldtwistermedaleu,omitempty" bson:"goldtwistermedaleu,omitempty"`
		ChristmasTreeLevelUpNY2019  int `json:"christmastreelevelupny2019,omitempty" bson:"christmastreelevelupny2019,omitempty"`
		MedalLavrinenko             int `json:"medallavrinenko,omitempty" bson:"medallavrinenko,omitempty"`
		MedalKolobanov              int `json:"medalkolobanov,omitempty" bson:"medalkolobanov,omitempty"`
		MedalLafayettePool          int `json:"medallafayettepool,omitempty" bson:"medallafayettepool,omitempty"`
		GoldClanRibbonEU            int `json:"goldclanribboneu,omitempty" bson:"goldclanribboneu,omitempty"`
		OlimpicGolden               int `json:"olimpicgolden,omitempty" bson:"olimpicgolden,omitempty"`
		MedalKnispel                int `json:"medalknispel,omitempty" bson:"medalknispel,omitempty"`
		Invader                     int `json:"invader,omitempty" bson:"invader,omitempty"`
		GoldTwisterMedalNA          int `json:"goldtwistermedalna,omitempty" bson:"goldtwistermedalna,omitempty"`
		MechanicEngineer            int `json:"mechanicengineer,omitempty" bson:"mechanicengineer,omitempty"`
		MarkOfMasteryII             int `json:"markofmasteryii,omitempty" bson:"markofmasteryii,omitempty"`
		FirstBlood                  int `json:"firstblood,omitempty" bson:"firstblood,omitempty"`
		MedalKay                    int `json:"medalkay,omitempty" bson:"medalkay,omitempty"`
		MedalOrlik                  int `json:"medalorlik,omitempty" bson:"medalorlik,omitempty"`
		MedalBrothersInArms         int `json:"medalbrothersinarms,omitempty" bson:"medalbrothersinarms,omitempty"`
		MedalAbrams                 int `json:"medalabrams,omitempty" bson:"medalabrams,omitempty"`
		MedalAtgm                   int `json:"medalatgm,omitempty" bson:"medalatgm,omitempty"`
		MainGun                     int `json:"maingun,omitempty" bson:"maingun,omitempty"`
		IronMan                     int `json:"ironman,omitempty" bson:"ironman,omitempty"`
		PlatinumClanRibbonEU        int `json:"platinumclanribboneu,omitempty" bson:"platinumclanribboneu,omitempty"`
		PlatinumClanRibbonSEA       int `json:"platinumclanribbonsea,omitempty" bson:"platinumclanribbonsea,omitempty"`
		Warrior                     int `json:"warrior,omitempty" bson:"warrior,omitempty"`
		GoldClanRibbonRU            int `json:"goldclanribbonru,omitempty" bson:"goldclanribbonru,omitempty"`
		MedalRadleyWalters          int `json:"medalradleywalters,omitempty" bson:"medalradleywalters,omitempty"`
		Raider                      int `json:"raider,omitempty" bson:"raider,omitempty"`
		ParticipantofNewStart       int `json:"participantofnewstart,omitempty" bson:"participantofnewstart,omitempty"`
		DiamondClanRibbon           int `json:"diamondclanribbon,omitempty" bson:"diamondclanribbon,omitempty"`
		MedalBillotte               int `json:"medalbillotte,omitempty" bson:"medalbillotte,omitempty"`
		PlatinumTwisterMedalEU      int `json:"platinumtwistermedaleu,omitempty" bson:"platinumtwistermedaleu,omitempty"`
		Diehard                     int `json:"diehard,omitempty" bson:"diehard,omitempty"`
		MasterofContinents          int `json:"masterofcontinents,omitempty" bson:"masterofcontinents,omitempty"`
		Evileye                     int `json:"evileye,omitempty" bson:"evileye,omitempty"`
		Cadet                       int `json:"cadet,omitempty" bson:"cadet,omitempty"`
		SupremacyHunter             int `json:"supremacyhunter,omitempty" bson:"supremacyhunter,omitempty"`
		ContinentalContender        int `json:"continentalcontender,omitempty" bson:"continentalcontender,omitempty"`
		Steelwall                   int `json:"steelwall,omitempty" bson:"steelwall,omitempty"`
		SupremacyLegend             int `json:"supremacylegend,omitempty" bson:"supremacylegend,omitempty"`
		Punisher                    int `json:"punisher,omitempty" bson:"punisher,omitempty"`
		ESport                      int `json:"esport,omitempty" bson:"esport,omitempty"`
		PlatinumTwisterMark         int `json:"platinumtwistermark,omitempty" bson:"platinumtwistermark,omitempty"`
		GoldClanRibbonNA            int `json:"goldclanribbonna,omitempty" bson:"goldclanribbonna,omitempty"`
		MedalPoppel                 int `json:"medalpoppel,omitempty" bson:"medalpoppel,omitempty"`
		MechanicEngineer6           int `json:"mechanicengineer6,omitempty" bson:"mechanicengineer6,omitempty"`
		MechanicEngineer4           int `json:"mechanicengineer4,omitempty" bson:"mechanicengineer4,omitempty"`
		GoldTwisterMedalSEA         int `json:"goldtwistermedalsea,omitempty" bson:"goldtwistermedalsea,omitempty"`
		MechanicEngineer2           int `json:"mechanicengineer2,omitempty" bson:"mechanicengineer2,omitempty"`
		MechanicEngineer3           int `json:"mechanicengineer3,omitempty" bson:"mechanicengineer3,omitempty"`
		MechanicEngineer0           int `json:"mechanicengineer0,omitempty" bson:"mechanicengineer0,omitempty"`
		MechanicEngineer1           int `json:"mechanicengineer1,omitempty" bson:"mechanicengineer1,omitempty"`
		MechanicEngineer5           int `json:"mechanicengineer5,omitempty" bson:"mechanicengineer5,omitempty"`
		MedalTarczay                int `json:"medaltarczay,omitempty" bson:"medaltarczay,omitempty"`
		Sinai                       int `json:"sinai,omitempty" bson:"sinai,omitempty"`
		PattonValley                int `json:"pattonvalley,omitempty" bson:"pattonvalley,omitempty"`
		MedalDeLanglade             int `json:"medaldelanglade,omitempty" bson:"medaldelanglade,omitempty"`
		DiamondTwisterMedal         int `json:"diamondtwistermedal,omitempty" bson:"diamondtwistermedal,omitempty"`
		Beasthunter                 int `json:"beasthunter,omitempty" bson:"beasthunter,omitempty"`
		SupremacyVeteran            int `json:"supremacyveteran,omitempty" bson:"supremacyveteran,omitempty"`
		Kamikaze                    int `json:"kamikaze,omitempty" bson:"kamikaze,omitempty"`
		OlimpicBronze               int `json:"olimpicbronze,omitempty" bson:"olimpicbronze,omitempty"`
		MedalTournamentOffseason3   int `json:"medaltournamentoffseason3,omitempty" bson:"medaltournamentoffseason3,omitempty"`
		PlatinumClanRibbonRU        int `json:"platinumclanribbonru,omitempty" bson:"platinumclanribbonru,omitempty"`
		MedalOskin                  int `json:"medaloskin,omitempty" bson:"medaloskin,omitempty"`
		Invincible                  int `json:"invincible,omitempty" bson:"invincible,omitempty"`
		PlatinumClanRibbonNA        int `json:"platinumclanribbonna,omitempty" bson:"platinumclanribbonna,omitempty"`
		PlatinumTwisterMedalRU      int `json:"platinumtwistermedalru,omitempty" bson:"platinumtwistermedalru,omitempty"`
		ContinentalViceChampion     int `json:"continentalvicechampion,omitempty" bson:"continentalvicechampion,omitempty"`
		OlimpicSilver               int `json:"olimpicsilver,omitempty" bson:"olimpicsilver,omitempty"`
		MarkOfMasteryI              int `json:"markofmasteryi,omitempty" bson:"markofmasteryi,omitempty"`
		ContinentalCompetitor       int `json:"continentalcompetitor,omitempty" bson:"continentalcompetitor,omitempty"`
		MedalTournamentSummerSeason int `json:"medaltournamentsummerseason,omitempty" bson:"medaltournamentsummerseason,omitempty"`
		Mousebane                   int `json:"mousebane,omitempty" bson:"mousebane,omitempty"`
		MedalBrunoPietro            int `json:"medalbrunopietro,omitempty" bson:"medalbrunopietro,omitempty"`
		MedalTournamentSpringSeason int `json:"medaltournamentspringseason,omitempty" bson:"medaltournamentspringseason,omitempty"`
		GoldTwisterMark             int `json:"goldtwistermark,omitempty" bson:"goldtwistermark,omitempty"`
		CollectorWarhammer          int `json:"collectorwarhammer,omitempty" bson:"collectorwarhammer,omitempty"`
		MarkOfMasteryIII            int `json:"markofmasteryiii,omitempty" bson:"markofmasteryiii,omitempty"`
		MedalLeClerc                int `json:"medalleclerc,omitempty" bson:"medalleclerc,omitempty"`
		MedalTournamentProfessional int `json:"medaltournamentprofessional,omitempty" bson:"medaltournamentprofessional,omitempty"`
		MedalCommunityChampion      int `json:"medalcommunitychampion,omitempty" bson:"medalcommunitychampion,omitempty"`
		DiamondTwisterMark          int `json:"diamondtwistermark,omitempty" bson:"diamondtwistermark,omitempty"`
		PlatinumTwisterMedalNA      int `json:"platinumtwistermedalna,omitempty" bson:"platinumtwistermedalna,omitempty"`
		HandOfDeath                 int `json:"handofdeath,omitempty" bson:"handofdeath,omitempty"`
		Huntsman                    int `json:"huntsman,omitempty" bson:"huntsman,omitempty"`
		Camper                      int `json:"camper,omitempty" bson:"camper,omitempty"`
		MedalNikolas                int `json:"medalnikolas,omitempty" bson:"medalnikolas,omitempty"`
		AndroidTest                 int `json:"androidtest,omitempty" bson:"androidtest,omitempty"`
		Sturdy                      int `json:"sturdy,omitempty" bson:"sturdy,omitempty"`
		MedalTwitch                 int `json:"medaltwitch,omitempty" bson:"medaltwitch,omitempty"`
		MedalWGfestTicket           int `json:"medalwgfestticket,omitempty" bson:"medalwgfestticket,omitempty"`
		ChampionofNewStart          int `json:"championofnewstart,omitempty" bson:"championofnewstart,omitempty"`
	} `json:"achievements"`
}
