name: Fly Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy app to production
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c cache.fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_CACHE }}
      - run: flyctl deploy --remote-only -c live.fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_LIVE }}
